location             = "eastus"
resource_group_name  = "red-team-lab-rg"
allowed_admin_cidr   = "203.0.113.5/32"
ssh_public_key_path  = "~/.ssh/id_rsa.pub"
kali_vm_name         = "kali-vm"
target_vm_name       = "target-vm"
kali_vm_size         = "Standard_B2ms"
target_vm_size       = "Standard_B2s"
kali_image_publisher = "kali-linux"
kali_image_offer     = "kali"
kali_image_sku       = "kali-2026-1"
kali_image_version   = "2026.1.0"
# Change the target image to a vulnerable OS or custom image as needed.
target_image_publisher = "Canonical"
target_image_offer     = "0001-com-ubuntu-server-jammy-daily"
target_image_sku       = "22_04-daily-lts-gen2"
target_image_version   = "22.04.202605150"
